ServerName ${SERVER_NAME}

Listen 8080

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

<VirtualHost *:8080>
    ServerName ${SERVER_NAME}

    DocumentRoot /srv/static

    <Directory /srv/static>
        Require all granted
    </Directory>

    ProxyPass        /api/ http://127.0.0.1:8000/api/
    ProxyPassReverse /api/ http://127.0.0.1:8000/api/
</VirtualHost>
